export const createLgeTypes = {
    CreateLge: [
        { name: 'id', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'tokenContractAddress', type: 'string' },
        { name: 'collateralTokenAddress', type: 'string' },
        { name: 'tokenAmount', type: 'string' },
        { name: 'collateralAmount', type: 'string' },
        { name: 'tokenStartWeight', type: 'int' },
        { name: 'tokenEndWeight', type: 'int' },
        { name: 'collateralStartWeight', type: 'int' },
        { name: 'collateralEndWeight', type: 'int' },
        { name: 'swapFeePercentage', type: 'string' },
        { name: 'tokenIconUrl', type: 'string' },
        { name: 'bannerImageUrl', type: 'string' },
        { name: 'websiteUrl', type: 'string' },
        { name: 'telegramUrl', type: 'string' },
        { name: 'twitterUrl', type: 'string' },
        { name: 'discordUrl', type: 'string' },
        { name: 'mediumUrl', type: 'string' },
        { name: 'startDate', type: 'string' },
        { name: 'endDate', type: 'string' },
    ],
};

export const updateLbpEventTypes = {
    UpdateLbpEvent: [
        { name: 'id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'tokenIconUrl', type: 'string' },
        { name: 'websiteUrl', type: 'string' },
        { name: 'telegramUrl', type: 'string' },
        { name: 'twitterUrl', type: 'string' },
        { name: 'mediumUrl', type: 'string' },
        { name: 'discordUrl', type: 'string' },
        { name: 'adminAddresses', type: 'string[]' },
    ],
};
