scalar Date
scalar GqlBigNumber
scalar Bytes
scalar BigInt
scalar BigDecimal
scalar JSON
scalar AmountHumanReadable

input GqlTokenAmountHumanReadable {
    address: String!
    amount: AmountHumanReadable!
}
