extend type Query {
    poolGetPool(id: String!): GqlPoolBase!
    poolGetPools(
        first: Int
        skip: Int
        orderBy: GqlPoolOrderBy
        orderDirection: GqlPoolOrderDirection
        where: GqlPoolFilter
    ): [GqlPoolBase!]!
}

extend type Mutation {
    poolSyncAllPoolsFromSubgraph: [String!]!
    poolLoadOnChainDataForAllPools: String!
    poolLoadOnChainDataForPoolsWithActiveUpdates: String!
    poolUpdateLiquidityValuesForAllPools: String!
    poolUpdateVolumeAndFeeValuesForAllPools: String!
    poolSyncSwapsForLast24Hours: String!
    poolSyncSanityPoolData: String!
    poolUpdateAprs: String!
}

interface GqlPoolBase {
    #fields that never change after creation
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!

    dynamicData: GqlPoolDynamicData!
}

type GqlPoolDynamicData {
    poolId: ID!

    #fields that change rarely
    swapFee: BigDecimal!
    swapEnabled: Boolean!
    #fields that change often
    totalShares: BigDecimal!
    #data that has USD values
    totalLiquidity: BigDecimal!
    volume24h: BigDecimal!
    fees24h: BigDecimal!
    apr: GqlPoolApr!
}

type GqlPoolInvestConfig {
    proportionalEnabled: Boolean!
    singleAssetEnabled: Boolean!
    options: [GqlPoolInvestOption!]!
}

type GqlPoolInvestOption {
    #we include the index because it is useful for constructing contract calls
    poolTokenIndex: Int!
    poolTokenAddress: String!

    # we use an array here for invest options where there are more than one option, but only one can be selected
    # - FTM/wFTM or ETH/wETH
    # - weighted boosted with nested phantom stable (bb-yv-USD) where you can only invest with DAI or USDC, not both at the same time
    tokenOptions: [GqlPoolToken!]!
}

type GqlPoolWithdrawConfig {
    proportionalEnabled: Boolean!
    singleAssetEnabled: Boolean!
    options: [GqlPoolWithdrawOption!]!
}

type GqlPoolWithdrawOption {
    poolTokenIndex: Int!
    poolTokenAddress: String!
    tokenOptions: [GqlPoolToken!]!
}

enum GqlPoolNestingType {
    NO_NESTING
    HAS_SOME_PHANTOM_BPT
    HAS_ONLY_PHANTOM_BPT
}

type GqlPoolWeighted implements GqlPoolBase {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!
    dynamicData: GqlPoolDynamicData!

    tokens: [GqlPoolTokenUnion!]!
    nestingType: GqlPoolNestingType!
}

type GqlPoolLiquidityBootstrapping implements GqlPoolBase {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!
    dynamicData: GqlPoolDynamicData!

    tokens: [GqlPoolTokenUnion!]!
    nestingType: GqlPoolNestingType!
}

type GqlPoolStable implements GqlPoolBase {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!
    dynamicData: GqlPoolDynamicData!

    tokens: [GqlPoolToken!]!
    amp: BigInt!
}

type GqlPoolPhantomStable implements GqlPoolBase {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!
    dynamicData: GqlPoolDynamicData!
    tokens: [GqlPoolTokenUnion!]!
    nestingType: GqlPoolNestingType!
    amp: BigInt!
}

type GqlPoolElement implements GqlPoolBase {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!
    dynamicData: GqlPoolDynamicData!
    tokens: [GqlPoolToken!]!

    #element specific fields
    unitSeconds: BigInt!
    principalToken: Bytes!
    baseToken: Bytes!
}

type GqlPoolLinear implements GqlPoolBase {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    investConfig: GqlPoolInvestConfig!
    withdrawConfig: GqlPoolWithdrawConfig!
    dynamicData: GqlPoolDynamicData!
    tokens: [GqlPoolToken!]!

    #linear specific fields
    mainIndex: Int!
    wrappedIndex: Int!
    upperTarget: BigInt!
    lowerTarget: BigInt!
}

type GqlPoolLinearNested {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    tokens: [GqlPoolToken!]!

    totalShares: BigDecimal!
    totalLiquidity: BigDecimal!

    #linear specific fields
    mainIndex: Int!
    wrappedIndex: Int!
    upperTarget: BigInt!
    lowerTarget: BigInt!
}

type GqlPoolPhantomStableNested {
    id: ID!
    name: String!
    symbol: String!
    address: Bytes!
    owner: Bytes!
    factory: Bytes
    createdAt: Int!
    tokens: [GqlPoolTokenPhantomStableNestedUnion!]!
    nestingType: GqlPoolNestingType!

    totalShares: BigDecimal!
    totalLiquidity: BigDecimal!
}

union GqlPoolUnion =
      GqlPoolWeighted
    | GqlPoolStable
    | GqlPoolLinear
    | GqlPoolPhantomStable
    | GqlPoolElement
    | GqlPoolLiquidityBootstrapping
union GqlPoolNestedUnion = GqlPoolLinearNested | GqlPoolPhantomStableNested

union GqlPoolTokenUnion = GqlPoolToken | GqlPoolTokenPhantomStable | GqlPoolTokenLinear
union GqlPoolTokenPhantomStableNestedUnion = GqlPoolToken | GqlPoolTokenLinear

interface GqlPoolTokenBase {
    id: ID!
    address: String!
    balance: BigDecimal!
    decimals: Int!
    name: String!
    symbol: String!
    priceRate: BigDecimal!
    weight: BigDecimal
}

type GqlPoolToken implements GqlPoolTokenBase {
    id: ID!
    address: String!
    decimals: Int!
    name: String!
    symbol: String!

    #dynamic data
    balance: BigDecimal!
    priceRate: BigDecimal!
    weight: BigDecimal
}

type GqlPoolTokenLinear implements GqlPoolTokenBase {
    id: ID!
    address: String!
    balance: BigDecimal!
    decimals: Int!
    name: String!
    symbol: String!
    priceRate: BigDecimal!
    weight: BigDecimal

    pool: GqlPoolLinearNested!
    #the proportional balances of the underlying tokens, computed as the fraction balance / totalShares
    mainTokenBalance: BigDecimal!
    wrappedTokenBalance: BigDecimal!
    totalMainTokenBalance: BigDecimal! # mainTokenBalance + wrappedTokenBalance * priceRate
}

type GqlPoolTokenPhantomStable implements GqlPoolTokenBase {
    id: ID!
    address: String!
    balance: BigDecimal!
    decimals: Int!
    name: String!
    symbol: String!
    priceRate: BigDecimal!
    weight: BigDecimal

    pool: GqlPoolPhantomStableNested!
}

type GqlPoolLinearPoolData {
    id: ID!
    address: String!
    symbol: String!
    priceRate: String!
    mainToken: GqlPoolLinearPoolMainToken!
    wrappedToken: GqlPoolLinearPoolWrappedToken!
    unwrappedTokenAddress: String!
    totalSupply: String!
    balance: String!
    poolToken: String!
    mainTokenTotalBalance: String!
}

type GqlPoolStablePhantomPoolData {
    id: ID!
    address: String!
    symbol: String!
    tokens: [GqlPoolToken!]!
    totalSupply: String!
    balance: String!
}

type GqlPoolLinearPoolMainToken {
    address: String!
    index: Int!
    balance: String!
    totalSupply: String!
    name: String!
    symbol: String!
    decimals: Int!
}

type GqlPoolLinearPoolWrappedToken {
    address: String!
    index: Int!
    balance: String!
    totalSupply: String!
    priceRate: String!
    name: String!
    symbol: String!
    decimals: Int!
}

type GqlPoolApr {
    total: BigDecimal!
    swapApr: BigDecimal!
    nativeRewardApr: BigDecimal!
    thirdPartyApr: BigDecimal!
    items: [GqlBalancePoolAprItem!]!
    hasRewardApr: Boolean!
}

type GqlPoolAprItem {
    title: String!
    apr: BigDecimal!
    subItems: [GqlBalancePoolAprSubItem!]
}

type GqlPoolAprSubItem {
    title: String!
    apr: BigDecimal!
}

enum GqlPoolOrderBy {
    totalLiquidity
    totalShares
    volume24h
    fees24h
}

enum GqlPoolOrderDirection {
    asc
    desc
}

input GqlPoolFilter {
    categoryIn: [GqlPoolFilterCategory!]
    categoryNotIn: [GqlPoolFilterCategory!]
    tokensIn: [String!]
    tokensNotIn: [String!]
    poolTypeIn: [GqlPoolFilterType!]
    poolTypeNotIn: [GqlPoolFilterType!]
}

enum GqlPoolFilterCategory {
    INCENTIVIZED
}

enum GqlPoolFilterType {
    WEIGHTED
    STABLE
    META_STABLE
    PHANTOM_STABLE
    ELEMENT
    LINEAR
    UNKNOWN
    LIQUIDITY_BOOTSTRAPPING
    INVESTMENT
}
