extend type Query {
    beetsGetProtocolData: GqlBeetsProtocolData!
    beetsGetBeetsFarms: [GqlBeetsFarm!]!
    beetsGetUserDataForFarm(farmId: String!): GqlBeetsFarmUser
    beetsGetUserDataForAllFarms: [GqlBeetsFarmUser!]!
    beetsGetConfig: GqlBeetsConfig!
}

type GqlBeetsProtocolData {
    totalLiquidity: BigDecimal!
    totalSwapVolume: BigDecimal!
    totalSwapFee: BigDecimal!
    poolCount: BigInt!
    beetsPrice: BigDecimal!
    fbeetsPrice: BigDecimal!
    circulatingSupply: BigDecimal!
    marketCap: BigDecimal!
    swapFee24h: BigDecimal!
    swapVolume24h: BigDecimal!
}

type GqlBeetsFarm {
    id: ID!
    pair: Bytes!
    allocPoint: Int!
    slpBalance: BigInt!
    userCount: BigInt!
    block: BigInt!
    lastRewardBlock: BigInt!
    timestamp: BigInt!
    masterChef: GqlBeetsMasterChef!
    rewarder: GqlBeetsRewarder
}

type GqlBeetsMasterChef {
    id: ID!
    beetsPerBlock: BigInt!
    totalAllocPoint: Int!
}

type GqlBeetsRewarder {
    id: ID!
    rewardPerSecond: BigInt!
    rewardToken: Bytes!
    tokens: [GqlBeetsRewarderToken!]!
}

type GqlBeetsRewarderToken {
    token: Bytes!
    symbol: String!
    tokenPrice: Float!
    rewardPerSecond: BigInt!
}

type GqlBeetsFarmUser {
    id: ID!
    address: Bytes!
    amount: BigInt!
    beetsHarvested: BigInt!
    farmId: ID!
    rewardDebt: BigInt!
    timestamp: BigInt!
}

type GqlBeetsConfig {
    incentivizedPools: [String!]!
    pausedPools: [String!]!
    blacklistedPools: [String!]!
    excludedPools: [String!]!
    featuredPools: [String!]!
    homeFeaturedPools: [GqlBeetsConfigFeaturedPool!]!
    homeNewsItems: [GqlBeetsConfigNewsItem!]!
    homeEducationItems: [GqlBeetsConfigNewsItem!]!
    poolFilters: [GqlBeetsConfigPoolFilterItem!]!
    blacklistedTokens: [String!]!
}

type GqlBeetsConfigFeaturedPool {
    poolId: String!
    image: String!
    description: String
}

type GqlBeetsConfigNewsItem {
    title: String!
    image: String!
    publishDate: String!
    url: String!
    description: String!
}

type GqlBeetsConfigPoolFilterItem {
    id: ID!
    title: String!
    pools: [String!]!
}
