extend type Query {
    tokenPriceGetCurrentPrices: [GqlTokenPrice!]!
    tokenPriceGetHistoricalPrices(addresses: [String!]!): [GqlHistoricalTokenPrice!]!
}

extend type Mutation {
    reloadTokenPrices: Boolean
}

type GqlTokenPrice {
    address: String!
    price: Float!
}

type GqlHistoricalTokenPrice {
    address: String!
    prices: [GqlHistoricalTokenPriceEntry!]!
}

type GqlHistoricalTokenPriceEntry {
    timestamp: String!
    price: Float!
}
