query SonicStakings(
    $skip: Int
    $first: Int
    $orderBy: SonicStaking_orderBy
    $orderDirection: OrderDirection
    $where: SonicStaking_filter
    $block: Block_height
) {
    sonicStakings(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...SonicStaking
    }
}

query Validators(
    $skip: Int
    $first: Int
    $orderBy: Validator_orderBy
    $orderDirection: OrderDirection
    $where: Validator_filter
    $block: Block_height
) {
    validators(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...Validator
    }
}

query SonicStakingSnapshots(
    $skip: Int
    $first: Int
    $orderBy: SonicStakingSnapshot_orderBy
    $orderDirection: OrderDirection
    $where: SonicStakingSnapshot_filter
    $block: Block_height
) {
    sonicStakingSnapshots(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...SonicStakingSnapshot
    }
}

fragment SonicStaking on SonicStaking {
    totalProtocolFee
}

fragment Validator on Validator {
    id
    amountAssetsDelegated
}

fragment SonicStakingSnapshot on SonicStakingSnapshot {
    id
    snapshotTimestamp
    totalPool
    totalAssets
    totalDelegated
    exchangeRate
    rewardsClaimed24h
    protocolFee24h
}
