version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - yarn install
            - rm -rf node_modules/@balancer-labs/sor/test
            - rm -rf node_modules/@balancer-labs/sor/src
    build:
        commands:
            - yarn prisma generate
            - yarn prisma migrate deploy
            - yarn build
            - yarn cleanup-console
    post_build:
        commands:
            - yarn install --prod
            - echo Build completed on `date`
#      - echo Pushing to graph cdn
#      - npx graphcdn push
cache:
    paths:
        - 'node_modules/**/*'
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
        - .ebextensions/**/*
