version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run generate
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - node_modules/**/*
    - dist/**/*
    - Procfile