version: 0.2
env:
    variables:
        V3_SUBGRAPH: 'https://api.studio.thegraph.com/proxy/31386/balancer-v3-sepolia/version/latest'
        V3_POOLS_SUBGRAPH: 'https://api.studio.thegraph.com/proxy/31386/balancer-pools-v3-sepolia/version/latest'
        BALANCER_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2'
        MASTERCHEF_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/masterchefv2'
        RELIQUARY_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/reliquary'
        BLOCKS_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/fantom-blocks'
        BEETS_BAR_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/beets-bar'
        YEARN_VAULTS_ENDPOINT: 'https://api.yexporter.io/v1/chains/250/vaults/all'
        SUBGRAPH_ORIG: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/beets-bar'
        GAUGE_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-gauges-optimism'
        USER_SNAPSHOT_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/user-bpt-balances-fantom'
        VEBALLOCKS_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-gauges'
        SFTMX_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/sftmx'
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - yarn install
    build:
        commands:
            - yarn generate
            - yarn prisma generate
            - yarn prisma migrate deploy
            - yarn build
    post_build:
        commands:
            - rm -fr node_modules
            - yarn install --prod
            - echo Build completed on `date`
#      - echo Pushing to graph cdn
#      - npx graphcdn push
cache:
    paths:
        - 'node_modules/**/*'
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
        - .ebextensions/**/*
