version: 0.2
env:
    variables:
        COW_AMM_SUBGRAPH: https://api.studio.thegraph.com/proxy/75376/balancer-cow-amm-sepolia/version/latest
        V3_SUBGRAPH: https://api.studio.thegraph.com/query/31386/balancer-v3-sepolia-6th/version/latest
        V3_POOLS_SUBGRAPH: https://api.studio.thegraph.com/query/31386/balancer-pools-v3-sepolia-5th/version/latest
        BALANCER_SUBGRAPH: https://api.studio.thegraph.com/query/75376/balancer-v2/version/latest
        MASTERCHEF_SUBGRAPH: https://api.studio.thegraph.com/query/73674/masterchefv2/version/latest
        BLOCKS_SUBGRAPH: https://api.studio.thegraph.com/query/48427/ethereum-blocks/version/latest
        BEETS_BAR_SUBGRAPH: https://api.studio.thegraph.com/query/73674/beets-bar/version/latest
        GAUGE_SUBGRAPH: https://api.studio.thegraph.com/query/75376/balancer-gauges/version/latest
        RELIQUARY_SUBGRAPH: https://api.studio.thegraph.com/query/73674/reliquary/version/latest
        SFTMX_SUBGRAPH: https://api.studio.thegraph.com/query/73674/sftmx/version/latest
        AURA_SUBGRAPH: https://data.aura.finance/graphql
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - mkdir -p cached_node_modules
            - cp -r cached_node_modules/ node_modules
            - yarn install
    build:
        commands:
            - yarn generate
            - yarn prisma generate
            - yarn prisma migrate deploy
            - yarn build
            - yarn cleanup-console
    post_build:
        commands:
            - cp -r node_modules cached_node_modules
            - yarn install --prod
            - echo Build completed on `date`
#      - echo Pushing to graph cdn
#      - npx graphcdn push
cache:
    paths:
        - 'cached_node_modules/**/*'
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
        - .ebextensions/**/*
