version: 0.2
env:
    variables:
        COW_AMM_SUBGRAPH: https://api.studio.thegraph.com/proxy/75376/balancer-cow-amm-sepolia/version/latest
        V3_SUBGRAPH: https://api.studio.thegraph.com/query/31386/balancer-v3-sepolia-6th/version/latest
        V3_POOLS_SUBGRAPH: https://api.studio.thegraph.com/query/31386/balancer-pools-v3-sepolia-5th/version/latest
        BALANCER_SUBGRAPH: https://api.studio.thegraph.com/query/75376/balancer-v2/version/latest
        MASTERCHEF_SUBGRAPH: https://api.studio.thegraph.com/query/73674/masterchefv2/version/latest
        BLOCKS_SUBGRAPH: https://api.studio.thegraph.com/query/48427/ethereum-blocks/version/latest
        BEETS_BAR_SUBGRAPH: https://api.studio.thegraph.com/query/73674/beets-bar/version/latest
        GAUGE_SUBGRAPH: https://api.studio.thegraph.com/query/75376/balancer-gauges/version/latest
        RELIQUARY_SUBGRAPH: https://api.studio.thegraph.com/query/73674/reliquary/version/latest
        SFTMX_SUBGRAPH: https://api.studio.thegraph.com/query/73674/sftmx/version/latest
        AURA_SUBGRAPH: https://data.aura.finance/graphql
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - mkdir -p node_modules
            - PROJECT_NAME=$(echo $CODEBUILD_BUILD_ID | cut -d ':' -f 1)
            - echo "Project name: $PROJECT_NAME"
            - CACHE_LOCATION=$(aws codebuild batch-get-projects --names $PROJECT_NAME --query "projects[0].cache.location" --output text)
            - echo "Cache location: $CACHE_LOCATION"
            - BUCKET_NAME=$(echo $CACHE_LOCATION | cut -d '/' -f 1)
            - echo "Bucket name: $BUCKET_NAME"
            - aws s3 cp s3://$BUCKET_NAME/node_modules_cache/ node_modules --recursive # Download node_modules from S3 if exists
            - yarn install
            - aws s3 cp node_modules s3://$BUCKET_NAME/node_modules_cache/ --recursive # Upload node_modules to S3
    build:
        commands:
            - yarn generate
            - yarn prisma generate
            - yarn prisma migrate deploy
            - yarn build
            - yarn cleanup-console
    post_build:
        commands:
            - yarn install --prod
            - echo Build completed on `date`
#      - echo Pushing to graph cdn
#      - npx graphcdn push
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
        - .ebextensions/**/*
