extend type Query {
    configGetNewsItems: [GqlConfigNewsItem!]!
}

type GqlConfigNewsItem {
    id: ID!
    timestamp: String!
    url: String!
    text: String!
    source: GqlConfigNewsItemSource!
    image: String
}

enum GqlConfigNewsItemSource {
    twitter
    discord
    medium
}
