import { gql } from 'graphql-request';
export const schema = gql`
    #
    # THIS FILE IS AUTOGENERATED — DO NOT EDIT IT
    #

    scalar BigInt

    enum Chain {
        ARBITRUM
        AVALANCHE
        BASE
        FANTOM
        FRAXTAL
        GNOSIS
        MAINNET
        MODE
        OPTIMISM
        POLYGON
        SEPOLIA
        SONIC
        ZKEVM
    }

    enum OrderDirection {
        asc
        desc
    }

    type Pool {
        address: String!
        chain: Chain!
        id: ID!
        protocolVersion: Int!
        totalLiquidity: Float!
        totalShares: BigInt!
    }

    input PoolFilter {
        chain: Chain!
        chain_in: [Chain!]
        chain_not_in: [Chain!]
        id: String!
        id_in: [String!]
        id_not_in: [String!]
        protocolVersion: Int!
        protocolVersion_in: [Int!]
        protocolVersion_not_in: [Int!]
        totalLiquidity_gt: Float
        totalLiquidity_gte: Float
        totalLiquidity_lt: Float
        totalLiquidity_lte: Float
    }

    enum PoolOrderBy {
        totalLiquidity
        totalShares
    }

    type Query {
        pool(chain: Chain!, id: String!): Pool
        pools(first: Int, orderBy: PoolOrderBy, orderDirection: OrderDirection, skip: Int, where: PoolFilter): [Pool!]!
    }
`;
