/*
 * THIS FILE IS AUTOGENERATED — DO NOT EDIT IT
 */
import { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type RequireFields<T, K extends keyof T> = { [X in Exclude<keyof T, K>]?: T[X] } & {
    [P in K]-?: NonNullable<T[P]>;
};
/** All built-in and custom scalars, mapped to their actual values */
export interface Scalars {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
    BigInt: string;
}

export type Chain =
    | 'ARBITRUM'
    | 'AVALANCHE'
    | 'BASE'
    | 'FANTOM'
    | 'FRAXTAL'
    | 'GNOSIS'
    | 'MAINNET'
    | 'MODE'
    | 'OPTIMISM'
    | 'POLYGON'
    | 'SEPOLIA'
    | 'SONIC'
    | 'ZKEVM';

export type OrderDirection = 'asc' | 'desc';

export interface Pool {
    __typename?: 'Pool';
    address: Scalars['String'];
    chain: Chain;
    id: Scalars['ID'];
    protocolVersion: Scalars['Int'];
    totalLiquidity: Scalars['Float'];
    totalShares: Scalars['BigInt'];
}

export interface PoolFilter {
    chain: Chain;
    chain_in?: InputMaybe<Array<Chain>>;
    chain_not_in?: InputMaybe<Array<Chain>>;
    id: Scalars['String'];
    id_in?: InputMaybe<Array<Scalars['String']>>;
    id_not_in?: InputMaybe<Array<Scalars['String']>>;
    protocolVersion: Scalars['Int'];
    protocolVersion_in?: InputMaybe<Array<Scalars['Int']>>;
    protocolVersion_not_in?: InputMaybe<Array<Scalars['Int']>>;
    totalLiquidity_gt?: InputMaybe<Scalars['Float']>;
    totalLiquidity_gte?: InputMaybe<Scalars['Float']>;
    totalLiquidity_lt?: InputMaybe<Scalars['Float']>;
    totalLiquidity_lte?: InputMaybe<Scalars['Float']>;
}

export type PoolOrderBy = 'totalLiquidity' | 'totalShares';

export interface Query {
    __typename?: 'Query';
    pool?: Maybe<Pool>;
    pools: Array<Pool>;
}

export interface QueryPoolArgs {
    chain: Chain;
    id: Scalars['String'];
}

export interface QueryPoolsArgs {
    first?: InputMaybe<Scalars['Int']>;
    orderBy?: InputMaybe<PoolOrderBy>;
    orderDirection?: InputMaybe<OrderDirection>;
    skip?: InputMaybe<Scalars['Int']>;
    where?: InputMaybe<PoolFilter>;
}

export type WithIndex<TObject> = TObject & Record<string, any>;
export type ResolversObject<TObject> = WithIndex<TObject>;

export type ResolverTypeWrapper<T> = Promise<T> | T;

export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
    resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
    | ResolverFn<TResult, TParent, TContext, TArgs>
    | ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
    parent: TParent,
    args: TArgs,
    context: TContext,
    info: GraphQLResolveInfo,
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
    parent: TParent,
    args: TArgs,
    context: TContext,
    info: GraphQLResolveInfo,
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
    parent: TParent,
    args: TArgs,
    context: TContext,
    info: GraphQLResolveInfo,
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
    subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
    resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
    subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
    resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
    | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
    | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = {}, TContext = {}, TArgs = {}> =
    | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
    | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
    parent: TParent,
    context: TContext,
    info: GraphQLResolveInfo,
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = {}, TContext = {}> = (
    obj: T,
    context: TContext,
    info: GraphQLResolveInfo,
) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs = {}> = (
    next: NextResolverFn<TResult>,
    parent: TParent,
    args: TArgs,
    context: TContext,
    info: GraphQLResolveInfo,
) => TResult | Promise<TResult>;

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = ResolversObject<{
    BigInt: ResolverTypeWrapper<Scalars['BigInt']>;
    Boolean: ResolverTypeWrapper<Scalars['Boolean']>;
    Chain: Chain;
    Float: ResolverTypeWrapper<Scalars['Float']>;
    ID: ResolverTypeWrapper<Scalars['ID']>;
    Int: ResolverTypeWrapper<Scalars['Int']>;
    OrderDirection: OrderDirection;
    Pool: ResolverTypeWrapper<Pool>;
    PoolFilter: PoolFilter;
    PoolOrderBy: PoolOrderBy;
    Query: ResolverTypeWrapper<{}>;
    String: ResolverTypeWrapper<Scalars['String']>;
}>;

/** Mapping between all available schema types and the resolvers parents */
export type ResolversParentTypes = ResolversObject<{
    BigInt: Scalars['BigInt'];
    Boolean: Scalars['Boolean'];
    Float: Scalars['Float'];
    ID: Scalars['ID'];
    Int: Scalars['Int'];
    Pool: Pool;
    PoolFilter: PoolFilter;
    Query: {};
    String: Scalars['String'];
}>;

export interface BigIntScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['BigInt'], any> {
    name: 'BigInt';
}

export type PoolResolvers<
    ContextType = any,
    ParentType extends ResolversParentTypes['Pool'] = ResolversParentTypes['Pool'],
> = ResolversObject<{
    address?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
    chain?: Resolver<ResolversTypes['Chain'], ParentType, ContextType>;
    id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
    protocolVersion?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
    totalLiquidity?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
    totalShares?: Resolver<ResolversTypes['BigInt'], ParentType, ContextType>;
    __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type QueryResolvers<
    ContextType = any,
    ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query'],
> = ResolversObject<{
    pool?: Resolver<
        Maybe<ResolversTypes['Pool']>,
        ParentType,
        ContextType,
        RequireFields<QueryPoolArgs, 'chain' | 'id'>
    >;
    pools?: Resolver<Array<ResolversTypes['Pool']>, ParentType, ContextType, RequireFields<QueryPoolsArgs, never>>;
}>;

export type Resolvers<ContextType = any> = ResolversObject<{
    BigInt?: GraphQLScalarType;
    Pool?: PoolResolvers<ContextType>;
    Query?: QueryResolvers<ContextType>;
}>;
