extend type Query {
    bxftmGetWithdrawalRequests(user: String!): [GqlBxFtmWithdrawalRequests!]!
    bxFtmGetStakingData: GqlBxFtmStakingData!
}

extend type Mutation {
    bxFtmSyncWithdrawalRequests: String!
    bxFtmSyncStakingData: String!
}

# TODO provide more info such as how much is staked on which validator
type GqlBxFtmStakingData {
    totalAmount: AmountHumanReadable!
    totalAmountStaked: AmountHumanReadable!
    totalAmountInPool: AmountHumanReadable!
    numberOfVaults: Int!
    undelegatePaused: Boolean!
    withdrawPaused: Boolean!
    maintenancePaused: Boolean!
    minDepositLimit: AmountHumanReadable!
    maxDepositLimit: AmountHumanReadable!
    exchangeRate: String!
    stakingApr: String!
    withdrawalDelay: Int!
}

type GqlBxFtmWithdrawalRequests {
    id: String!
    user: String!
    amount: AmountHumanReadable!
    requestTimestamp: Int!
    isWithdrawn: Boolean!
}
