export default [
    {
        inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256[]', name: '', type: 'uint256[]' },
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'uint256', name: '', type: 'uint256' },
        ],
        name: 'computeBalance',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256[]', name: 'balances', type: 'uint256[]' },
            { internalType: 'enum Rounding', name: 'rounding', type: 'uint8' },
        ],
        name: 'computeInvariant',
        outputs: [{ internalType: 'uint256', name: 'invariant', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'decimals',
        outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getAggregateFeePercentages',
        outputs: [
            { internalType: 'uint256', name: 'aggregateSwapFeePercentage', type: 'uint256' },
            { internalType: 'uint256', name: 'aggregateYieldFeePercentage', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getCurrentLiveBalances',
        outputs: [{ internalType: 'uint256[]', name: 'balancesLiveScaled18', type: 'uint256[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getFixedPriceLBPoolDynamicData',
        outputs: [
            {
                components: [
                    { internalType: 'uint256[]', name: 'balancesLiveScaled18', type: 'uint256[]' },
                    { internalType: 'uint256', name: 'staticSwapFeePercentage', type: 'uint256' },
                    { internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
                    { internalType: 'bool', name: 'isPoolInitialized', type: 'bool' },
                    { internalType: 'bool', name: 'isPoolPaused', type: 'bool' },
                    { internalType: 'bool', name: 'isPoolInRecoveryMode', type: 'bool' },
                    { internalType: 'bool', name: 'isSwapEnabled', type: 'bool' },
                ],
                internalType: 'struct FixedPriceLBPoolDynamicData',
                name: 'data',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getFixedPriceLBPoolImmutableData',
        outputs: [
            {
                components: [
                    { internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' },
                    { internalType: 'uint256[]', name: 'decimalScalingFactors', type: 'uint256[]' },
                    { internalType: 'uint256', name: 'startTime', type: 'uint256' },
                    { internalType: 'uint256', name: 'endTime', type: 'uint256' },
                    { internalType: 'uint256', name: 'projectTokenIndex', type: 'uint256' },
                    { internalType: 'uint256', name: 'reserveTokenIndex', type: 'uint256' },
                    { internalType: 'uint256', name: 'projectTokenRate', type: 'uint256' },
                ],
                internalType: 'struct FixedPriceLBPoolImmutableData',
                name: 'data',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getHookFlags',
        outputs: [
            {
                components: [
                    { internalType: 'bool', name: 'enableHookAdjustedAmounts', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeInitialize', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterInitialize', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallComputeDynamicSwapFee', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeSwap', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterSwap', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeAddLiquidity', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterAddLiquidity', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeRemoveLiquidity', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterRemoveLiquidity', type: 'bool' },
                ],
                internalType: 'struct HookFlags',
                name: 'hookFlags',
                type: 'tuple',
            },
        ],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getMaximumInvariantRatio',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getMaximumSwapFeePercentage',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getProjectToken',
        outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getProjectTokenRate',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getRate',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getReserveToken',
        outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getStaticSwapFeePercentage',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getTokenIndices',
        outputs: [
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'uint256', name: '', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getTokenInfo',
        outputs: [
            { internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' },
            {
                components: [
                    { internalType: 'enum TokenType', name: 'tokenType', type: 'uint8' },
                    { internalType: 'contract IRateProvider', name: 'rateProvider', type: 'address' },
                    { internalType: 'bool', name: 'paysYieldFees', type: 'bool' },
                ],
                internalType: 'struct TokenInfo[]',
                name: 'tokenInfo',
                type: 'tuple[]',
            },
            { internalType: 'uint256[]', name: 'balancesRaw', type: 'uint256[]' },
            { internalType: 'uint256[]', name: 'lastBalancesLiveScaled18', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getTokens',
        outputs: [{ internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'incrementNonce', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [],
        name: 'isProjectTokenSwapInBlocked',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isSwapEnabled',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'name',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
        name: 'nonces',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pendingOwner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'address', name: 'spender', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
            { internalType: 'uint256', name: 'deadline', type: 'uint256' },
            { internalType: 'uint8', name: 'v', type: 'uint8' },
            { internalType: 'bytes32', name: 'r', type: 'bytes32' },
            { internalType: 'bytes32', name: 's', type: 'bytes32' },
        ],
        name: 'permit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
        name: 'supportsInterface',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'symbol',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalSupply',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'transfer',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'from', type: 'address' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'transferFrom',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'version',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
] as const;
