export default [
    {
        inputs: [],
        name: 'getAggregateFeePercentages',
        outputs: [
            { internalType: 'uint256', name: 'aggregateSwapFeePercentage', type: 'uint256' },
            { internalType: 'uint256', name: 'aggregateYieldFeePercentage', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getCurrentLiveBalances',
        outputs: [{ internalType: 'uint256[]', name: 'balancesLiveScaled18', type: 'uint256[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getGradualWeightUpdateParams',
        outputs: [
            { internalType: 'uint256', name: 'startTime', type: 'uint256' },
            { internalType: 'uint256', name: 'endTime', type: 'uint256' },
            { internalType: 'uint256[]', name: 'startWeights', type: 'uint256[]' },
            { internalType: 'uint256[]', name: 'endWeights', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getHookFlags',
        outputs: [
            {
                components: [
                    { internalType: 'bool', name: 'enableHookAdjustedAmounts', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeInitialize', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterInitialize', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallComputeDynamicSwapFee', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeSwap', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterSwap', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeAddLiquidity', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterAddLiquidity', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallBeforeRemoveLiquidity', type: 'bool' },
                    { internalType: 'bool', name: 'shouldCallAfterRemoveLiquidity', type: 'bool' },
                ],
                internalType: 'struct HookFlags',
                name: 'hookFlags',
                type: 'tuple',
            },
        ],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getLBPoolDynamicData',
        outputs: [
            {
                components: [
                    { internalType: 'uint256[]', name: 'balancesLiveScaled18', type: 'uint256[]' },
                    { internalType: 'uint256', name: 'staticSwapFeePercentage', type: 'uint256' },
                    { internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
                    { internalType: 'bool', name: 'isPoolInitialized', type: 'bool' },
                    { internalType: 'bool', name: 'isPoolPaused', type: 'bool' },
                    { internalType: 'bool', name: 'isPoolInRecoveryMode', type: 'bool' },
                    { internalType: 'bool', name: 'isSwapEnabled', type: 'bool' },
                    { internalType: 'uint256[]', name: 'normalizedWeights', type: 'uint256[]' },
                ],
                internalType: 'struct LBPoolDynamicData',
                name: 'data',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getLBPoolImmutableData',
        outputs: [
            {
                components: [
                    { internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' },
                    { internalType: 'uint256[]', name: 'decimalScalingFactors', type: 'uint256[]' },
                    { internalType: 'uint256', name: 'startTime', type: 'uint256' },
                    { internalType: 'uint256', name: 'endTime', type: 'uint256' },
                    { internalType: 'uint256', name: 'projectTokenIndex', type: 'uint256' },
                    { internalType: 'uint256', name: 'reserveTokenIndex', type: 'uint256' },
                    { internalType: 'bool', name: 'isProjectTokenSwapInBlocked', type: 'bool' },
                    { internalType: 'uint256[]', name: 'startWeights', type: 'uint256[]' },
                    { internalType: 'uint256[]', name: 'endWeights', type: 'uint256[]' },
                    { internalType: 'uint256', name: 'reserveTokenVirtualBalance', type: 'uint256' },
                    { internalType: 'address', name: 'migrationRouter', type: 'address' },
                    { internalType: 'uint256', name: 'lockDurationAfterMigration', type: 'uint256' },
                    { internalType: 'uint256', name: 'bptPercentageToMigrate', type: 'uint256' },
                    { internalType: 'uint256', name: 'migrationWeightProjectToken', type: 'uint256' },
                    { internalType: 'uint256', name: 'migrationWeightReserveToken', type: 'uint256' },
                ],
                internalType: 'struct LBPoolImmutableData',
                name: 'data',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getMigrationParameters',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'migrationRouter', type: 'address' },
                    { internalType: 'uint256', name: 'lockDurationAfterMigration', type: 'uint256' },
                    { internalType: 'uint256', name: 'bptPercentageToMigrate', type: 'uint256' },
                    { internalType: 'uint256', name: 'migrationWeightProjectToken', type: 'uint256' },
                    { internalType: 'uint256', name: 'migrationWeightReserveToken', type: 'uint256' },
                ],
                internalType: 'struct MigrationParams',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getNormalizedWeights',
        outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getProjectToken',
        outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getRate',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getReserveToken',
        outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getReserveTokenVirtualBalance',
        outputs: [
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'uint256', name: '', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getStaticSwapFeePercentage',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getTokenIndices',
        outputs: [
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'uint256', name: '', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getTokenInfo',
        outputs: [
            { internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' },
            {
                components: [
                    { internalType: 'enum TokenType', name: 'tokenType', type: 'uint8' },
                    { internalType: 'contract IRateProvider', name: 'rateProvider', type: 'address' },
                    { internalType: 'bool', name: 'paysYieldFees', type: 'bool' },
                ],
                internalType: 'struct TokenInfo[]',
                name: 'tokenInfo',
                type: 'tuple[]',
            },
            { internalType: 'uint256[]', name: 'balancesRaw', type: 'uint256[]' },
            { internalType: 'uint256[]', name: 'lastBalancesLiveScaled18', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getTokens',
        outputs: [{ internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getWeightedPoolDynamicData',
        outputs: [
            {
                components: [
                    { internalType: 'uint256[]', name: 'balancesLiveScaled18', type: 'uint256[]' },
                    { internalType: 'uint256[]', name: 'tokenRates', type: 'uint256[]' },
                    { internalType: 'uint256', name: 'staticSwapFeePercentage', type: 'uint256' },
                    { internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
                    { internalType: 'bool', name: 'isPoolInitialized', type: 'bool' },
                    { internalType: 'bool', name: 'isPoolPaused', type: 'bool' },
                    { internalType: 'bool', name: 'isPoolInRecoveryMode', type: 'bool' },
                ],
                internalType: 'struct WeightedPoolDynamicData',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getWeightedPoolImmutableData',
        outputs: [
            {
                components: [
                    { internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' },
                    { internalType: 'uint256[]', name: 'decimalScalingFactors', type: 'uint256[]' },
                    { internalType: 'uint256[]', name: 'normalizedWeights', type: 'uint256[]' },
                ],
                internalType: 'struct WeightedPoolImmutableData',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isSwapEnabled',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'name',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pendingOwner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'symbol',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalSupply',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'version',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
] as const;
