extend type Query {
    sorGetSwaps(
        chain: GqlChain!
        tokenIn: String!
        tokenOut: String!
        swapType: GqlSorSwapType!
        swapAmount: BigDecimal! #expected in human readable form
        swapOptions: GqlSorSwapOptionsInput!
        graphTraversalConfig: GqlGraphTraversalConfigInput
    ): GqlSorGetSwapsResponse!
    sorGetBatchSwapForTokensIn(
        tokensIn: [GqlTokenAmountHumanReadable!]!
        tokenOut: String!
        swapOptions: GqlSorSwapOptionsInput!
    ): GqlSorGetBatchSwapForTokensInResponse!
}

enum GqlSorSwapType {
    EXACT_IN
    EXACT_OUT
}

input GqlSorSwapOptionsInput {
    timestamp: Int #used for caching purposes
    maxPools: Int
    forceRefresh: Boolean #don't use any cached responses
}

input GqlGraphTraversalConfigInput {
    maxDepth: Int # default 6
    maxNonBoostedPathDepth: Int # default 3
    maxNonBoostedHopTokensInBoostedPath: Int # default 2
    approxPathsToReturn: Int # default 5
    poolIdsToInclude: [String]
}

type GqlSorGetSwapsResponse {
    tokenIn: String!
    tokenOut: String!
    tokenAddresses: [String!]!
    swapType: GqlSorSwapType!
    swaps: [GqlSorSwap!]!
    tokenInAmount: AmountHumanReadable!
    tokenOutAmount: AmountHumanReadable!
    swapAmount: AmountHumanReadable!
    swapAmountScaled: BigDecimal!
    swapAmountForSwaps: BigDecimal
    returnAmount: AmountHumanReadable!
    returnAmountScaled: BigDecimal!
    returnAmountFromSwaps: BigDecimal
    returnAmountConsideringFees: BigDecimal!
    marketSp: String!
    routes: [GqlSorSwapRoute!]!
    effectivePrice: AmountHumanReadable!
    effectivePriceReversed: AmountHumanReadable!
    priceImpact: AmountHumanReadable!
}

type GqlSorSwap {
    poolId: String!
    assetInIndex: Int!
    assetOutIndex: Int!
    amount: String!
    userData: String!
}

type GqlSorSwapRoute {
    tokenIn: String!
    tokenInAmount: BigDecimal!
    tokenOut: String!
    tokenOutAmount: BigDecimal!
    share: Float!
    hops: [GqlSorSwapRouteHop!]!
}

type GqlSorSwapRouteHop {
    tokenIn: String!
    tokenInAmount: BigDecimal!
    tokenOut: String!
    tokenOutAmount: BigDecimal!
    poolId: String!
    pool: GqlPoolMinimal!
}

type GqlSorGetBatchSwapForTokensInResponse {
    tokenOutAmount: AmountHumanReadable!
    swaps: [GqlSorSwap!]!
    assets: [String!]!
}

type GqlCowSwapApiResponse {
    tokenAddresses: [String!]!
    swaps: [GqlSwap!]!
    swapAmount: String!
    swapAmountForSwaps: String!
    returnAmount: String!
    returnAmountFromSwaps: String!
    returnAmountConsideringFees: String!
    tokenIn: String!
    tokenOut: String!
    marketSp: String!
}

type GqlSwap {
    poolId: String!
    assetInIndex: Int!
    assetOutIndex: Int!
    amount: String!
    userData: String!
}
