extend type Query {
    beetsGetFbeetsRatio: String!

    beetsPoolGetReliquaryFarmSnapshots(id: String!, range: GqlPoolSnapshotDataRange!): [GqlReliquaryFarmSnapshot!]!

    userGetFbeetsBalance: GqlUserFbeetsBalance!
}

extend type Mutation {
    beetsSyncFbeetsRatio: String!

    beetsPoolLoadReliquarySnapshotsForAllFarms: String!
}

type GqlUserFbeetsBalance {
    id: String!
    totalBalance: AmountHumanReadable!
    walletBalance: AmountHumanReadable!
    stakedBalance: AmountHumanReadable!
}
