extend type Query {
    """
    Returns all pools for a given filter, specific for aggregators
    """
    poolGetAggregatorPools(
        first: Int
        skip: Int
        orderBy: GqlPoolOrderBy
        orderDirection: GqlPoolOrderDirection
        where: GqlPoolFilter
    ): [GqlPoolAggregator!]! @deprecated(reason: "Use aggregatorPools instead")

    """
    Returns all pools for a given filter, specific for aggregators
    """
    aggregatorPools(
        first: Int
        skip: Int
        orderBy: GqlPoolOrderBy
        orderDirection: GqlPoolOrderDirection
        where: GqlAggregatorPoolFilter
    ): [GqlPoolAggregator!]!
}

input GqlAggregatorPoolFilter {
    tokensIn: [String!]
    tokensNotIn: [String!] @deprecated
    poolTypeIn: [GqlPoolType!]
    poolTypeNotIn: [GqlPoolType!] @deprecated
    idIn: [String!]
    idNotIn: [String!] @deprecated
    chainIn: [GqlChain!]
    chainNotIn: [GqlChain!] @deprecated
    createTime: GqlPoolTimePeriod @deprecated
    protocolVersionIn: [Int!]
    includeHooks: [GqlHookType!]
    minTvl: Float
}

type GqlPoolAggregator {
    """
    The pool id. This is equal to the address for protocolVersion 3 pools
    """
    id: ID!
    """
    The chain on which the pool is deployed
    """
    chain: GqlChain!
    """
    The protocol version on which the pool is deployed, 1, 2 or 3
    """
    protocolVersion: Int!
    """
    The pool type, such as weighted, stable, etc.
    """
    type: GqlPoolType!
    """
    The name of the pool as per contract
    """
    name: String!
    """
    The token symbol of the pool as per contract
    """
    symbol: String!
    """
    The contract address of the pool.
    """
    address: Bytes!
    """
    The decimals of the BPT, usually 18
    """
    decimals: Int!
    """
    The wallet address of the owner of the pool. Pool owners can set certain properties like swapFees or AMP.
    """
    owner: Bytes @deprecated(reason: "Use swapFeeManager instead")
    """
    Account empowered to set static swap fees for a pool (when 0 on V2 swap fees are immutable, on V3 delegate to governance)
    """
    swapFeeManager: Bytes
    """
    Account empowered to pause/unpause the pool (or 0 to delegate to governance)
    """
    pauseManager: Bytes
    """
    Account empowered to set the pool creator fee percentage
    """
    poolCreator: Bytes
    """
    The factory contract address from which the pool was created.
    """
    factory: Bytes
    """
    The timestamp the pool was created.
    """
    createTime: Int!
    """
    The version of the pool type.
    """
    version: Int!
    """
    Returns all pool tokens, including BPTs and nested pools if there are any. Only one nested level deep.
    """
    poolTokens: [GqlPoolTokenDetail!]!
    """
    Dynamic data such as token balances, swap fees or volume
    """
    dynamicData: GqlPoolDynamicData!
    """
    Data specific to gyro/fx pools
    """
    alpha: String
    """
    Data specific to gyro/fx pools
    """
    beta: String
    """
    Data specific to gyro pools
    """
    sqrtAlpha: String
    """
    Data specific to gyro pools
    """
    sqrtBeta: String
    """
    Data specific to gyro pools
    """
    root3Alpha: String
    """
    Data specific to gyro pools
    """
    c: String
    """
    Data specific to gyro pools
    """
    s: String
    """
    Data specific to gyro/fx pools
    """
    lambda: String
    """
    Data specific to gyro pools
    """
    tauAlphaX: String
    """
    Data specific to gyro pools
    """
    tauAlphaY: String
    """
    Data specific to gyro pools
    """
    tauBetaX: String
    """
    Data specific to gyro pools
    """
    tauBetaY: String
    """
    Data specific to gyro pools
    """
    u: String
    """
    Data specific to gyro pools
    """
    v: String
    """
    Data specific to gyro pools
    """
    w: String
    """
    Data specific to gyro pools
    """
    z: String
    """
    Data specific to gyro pools
    """
    dSq: String
    """
    Data specific to fx pools
    """
    delta: String
    """
    Data specific to fx pools
    """
    epsilon: String
    """
    Data specific to stable pools
    """
    amp: BigInt
    """
    Liquidity management settings for v3 pools.
    """
    liquidityManagement: LiquidityManagement
    """
    Hook assigned to a pool
    """
    hook: GqlHook
    """
    QuantAmmWeighted specific fields
    """
    quantAmmWeightedParams: QuantAmmWeightedParams
    """
    The timestamp of the last user interaction
    """
    lastTimestamp: Int
    """
    ReClamm: The last virtual balances of the pool
    """
    lastVirtualBalances: [BigDecimal!]
    """
    ReClamm: Represents how fast the pool can move the virtual balances per day
    """
    dailyPriceShiftBase: BigDecimal
    """
    ReClamm: The centeredness margin of the pool
    """
    centerednessMargin: BigDecimal
    """
    ReClamm: The current fourth root price ratio, an interpolation of the price ratio state
    """
    currentFourthRootPriceRatio: BigDecimal
    """
    ReClamm: The fourth root price ratio at the start of an update
    """
    startFourthRootPriceRatio: BigDecimal
    """
    ReClamm: The fourth root price ratio at the end of an update
    """
    endFourthRootPriceRatio: BigDecimal
    """
    ReClamm: The timestamp when the update begins
    """
    priceRatioUpdateStartTime: Int
    """
    ReClamm: The timestamp when the update ends
    """
    priceRatioUpdateEndTime: Int
}
