extend type Query {
    beetsPoolGetReliquaryFarmSnapshots(
        id: String!
        range: GqlPoolSnapshotDataRange!
        chain: GqlChain!
    ): [GqlReliquaryFarmSnapshot!]!
}

extend type Mutation {
    beetsPoolLoadReliquarySnapshotsForAllFarms(chain: GqlChain!): String!
}
