extend type Query {
    blocksGetAverageBlockTime: Float! @deprecated
    blocksGetBlocksPerSecond: Float! @deprecated
    blocksGetBlocksPerDay: Float! @deprecated
    blocksGetBlocksPerYear: Float! @deprecated
}
