# Input types for the mutation
input LBPoolInput {
    address: String!
    chain: GqlChain!
}

input LBPMetadataInput {
    lbpName: String!
    description: String!
    tokenLogo: String!
    website: String!
    x: String
    discord: String
    telegram: String
    farcaster: String
}

input CreateLBPInput {
    poolContract: LBPoolInput!
    metadata: LBPMetadataInput!
}

type LBPPriceChartData {
    timestamp: Int!
    projectTokenBalance: Float!
    reserveTokenBalance: Float!
    projectTokenPrice: Float!
    reservePrice: Float!
    volume: Float!
    cumulativeVolume: Float!
    buyVolume: Float!
    sellVolume: Float!
    swapCount: Int!
    tvl: Float!
    fees: Float!
    cumulativeFees: Float!
}

type Query {
    lbpPriceChart(id: String!, chain: GqlChain!, dataPoints: Int): [LBPPriceChartData!]
    fixedLbpPriceChart(id: String!, chain: GqlChain!, dataPoints: Int): [LBPPriceChartData!]
}

type Mutation {
    createLBP(input: CreateLBPInput!, type: GqlPoolType): Boolean!
    lbpReloadLbps(chains: [GqlChain!]!): String!
    lbpReloadFixedLbps(chains: [GqlChain!]!): String!
}
