extend type Query {
    protocolMetricsChain(chain: GqlChain): GqlProtocolMetricsChain!
    protocolMetricsAggregated(chains: [GqlChain!]): GqlProtocolMetricsAggregated!
    latestSyncedBlocks: GqlLatestSyncedBlocks!
}

extend type Mutation {
    protocolCacheMetrics: String!
}

type GqlProtocolMetricsAggregated {
    totalLiquidity: BigDecimal!
    totalSwapVolume: BigDecimal! @deprecated(reason: "No replacement")
    totalSwapFee: BigDecimal! @deprecated(reason: "No replacement")
    poolCount: BigInt!
    swapFee24h: BigDecimal!
    swapVolume24h: BigDecimal!
    yieldCapture24h: BigDecimal!
    surplus24h: BigDecimal!
    numLiquidityProviders: BigInt!
    chains: [GqlProtocolMetricsChain!]!
}

type GqlProtocolMetricsChain {
    chainId: String!
    totalLiquidity: BigDecimal!
    totalSwapVolume: BigDecimal! @deprecated(reason: "No replacement")
    totalSwapFee: BigDecimal! @deprecated(reason: "No replacement")
    poolCount: BigInt!
    swapFee24h: BigDecimal!
    swapVolume24h: BigDecimal!
    yieldCapture24h: BigDecimal!
    surplus24h: BigDecimal!
    numLiquidityProviders: BigInt!
}

type GqlLatestSyncedBlocks {
    userWalletSyncBlock: BigInt!
    userStakeSyncBlock: BigInt!
    poolSyncBlock: BigInt!
}
