extend type Query {
    protocolMetricsChain(chain: GqlChain!): GqlProtocolMetricsChain!
    protocolMetricsAggregated(chains: [GqlChain!]!): GqlProtocolMetricsAggregated!
}

extend type Mutation {
    protocolCacheMetrics(chain: GqlChain!): String!
}

type GqlProtocolMetricsAggregated {
    totalLiquidity: BigDecimal!
    totalSwapVolume: BigDecimal! @deprecated(reason: "No replacement")
    totalSwapFee: BigDecimal! @deprecated(reason: "No replacement")
    poolCount: BigInt!
    swapFee24h: BigDecimal!
    swapVolume24h: BigDecimal!
    yieldCapture24h: BigDecimal!
    surplus24h: BigDecimal!
    numLiquidityProviders: BigInt!
    chains: [GqlProtocolMetricsChain!]!
}

type GqlProtocolMetricsChain {
    chainId: String!
    totalLiquidity: BigDecimal!
    totalSwapVolume: BigDecimal! @deprecated(reason: "No replacement")
    totalSwapFee: BigDecimal! @deprecated(reason: "No replacement")
    poolCount: BigInt!
    swapFee24h: BigDecimal!
    swapVolume24h: BigDecimal!
    yieldCapture24h: BigDecimal!
    surplus24h: BigDecimal!
    numLiquidityProviders: BigInt!
}
