extend type Query {
    """
    Get the staking data and status for stS
    """
    stsGetGqlStakedSonicData: GqlStakedSonicData!
    """
    Get snapshots for sftmx staking for a specific range
    """
    stsGetStakedSonicSnapshots(range: GqlStakedSonicSnapshotDataRange!): [GqlStakedSonicSnapshot!]!
}

type GqlStakedSonicData {
    """
    Total amount of S in custody of stS. Delegated S plus pool S.
    """
    totalAssets: AmountHumanReadable!

    """
    Total amount of S elegated to validators.
    """
    totalAssetsDelegated: AmountHumanReadable!
    """
    Total amount of S in the pool to be delegated.
    """
    totalAssetsPool: AmountHumanReadable!
    """
    The current rebasing APR for stS.
    """
    stakingApr: String!
    """
    The total protocol fee collected in the last 24 hours.
    """
    protocolFee24h: String!
    """
    The total rewards claimed in the last 24 hours.
    """
    rewardsClaimed24h: String!
    """
    Current exchange rate for stS -> S
    """
    exchangeRate: String!

    """
    A list of all the delegated validators.
    """
    delegatedValidators: [GqlStakedSonicDelegatedValidator!]!
}

type GqlStakedSonicDelegatedValidator {
    """
    The id of the validator.
    """
    validatorId: String!
    """
    The amount of S that has been delegated to this validator.
    """
    assetsDelegated: AmountHumanReadable!
}

enum GqlStakedSonicSnapshotDataRange {
    THIRTY_DAYS
    NINETY_DAYS
    ONE_HUNDRED_EIGHTY_DAYS
    ONE_YEAR
    ALL_TIME
}

type GqlStakedSonicSnapshot {
    id: ID!
    """
    The timestamp of the snapshot. Timestamp is end of day midnight.
    """
    timestamp: Int!
    """
    Total amount of S in custody of stS. Delegated S plus pool S.
    """
    totalAssets: AmountHumanReadable!
    """
    Total amount of S delegated to validators.
    """
    totalAssetsDelegated: AmountHumanReadable!
    """
    Total amount of S in the pool.
    """
    totalAssetsPool: AmountHumanReadable!
    """
    Current exchange rate for stS -> S
    """
    exchangeRate: String!
    """
    The total protocol fee collected during that day.
    """
    protocolFee24h: String!
    """
    The total rewards claimed during that day.
    """
    rewardsClaimed24h: String!
}
