extend type Mutation {
    userInitWalletBalancesForAllPools(chain: GqlChain): String!
    userSyncChangedWalletBalancesForAllPools: String!

    userInitStakedBalances(stakingTypes: [GqlPoolStakingType!]!): String!
    userSyncChangedStakedBalances: String!
}
