extend type Query {
    userGetPoolBalances: [GqlUserPoolBalance!]!
    userGetFbeetsBalance: GqlUserFbeetsBalance!
    userGetStaking: [GqlPoolStaking!]!
    userGetPoolJoinExits(first: Int = 10, skip: Int = 0, poolId: String!): [GqlPoolJoinExit!]!
    userGetSwaps(first: Int = 10, skip: Int = 0, poolId: String!): [GqlPoolSwap!]!
    userGetPoolSnapshots(poolId: String!, numDays: Int!): [GqlUserPoolSnapshot!]!
}

extend type Mutation {
    userSyncBalance(poolId: String!): String!
    userSyncBalanceAllPools: String!

    userInitWalletBalancesForAllPools: String!
    userInitWalletBalancesForPool(poolId: String!): String!
    userSyncChangedWalletBalancesForAllPools: String!

    userInitStakedBalances: String!
    userSyncChangedStakedBalances: String!
}

type GqlUserPoolBalance {
    poolId: String!
    tokenAddress: String!
    tokenPrice: Float!
    totalBalance: AmountHumanReadable!
    walletBalance: AmountHumanReadable!
    stakedBalance: AmountHumanReadable!
}

type GqlUserFbeetsBalance {
    id: String!
    totalBalance: AmountHumanReadable!
    walletBalance: AmountHumanReadable!
    stakedBalance: AmountHumanReadable!
}

type GqlUserPoolSnapshot {
    id: ID!
    timestamp: Int!
    walletBalance: AmountHumanReadable!
    gaugeBalance: AmountHumanReadable!
    farmBalance: AmountHumanReadable!
    totalBalance: AmountHumanReadable!
    percentShare: Float!
    valueUSD: AmountHumanReadable!
    fees24h: AmountHumanReadable!
}
