extend type Mutation {
    userInitWalletBalancesForAllPools: String!
    userInitWalletBalancesForPool(poolId: String!): String!
    userSyncWalletBalancesForAllPools: String!
    userInitWalletBalancesForMissingPools: String!
}
