extend type Query {
    userGetPoolBalances: [GqlUserPoolBalance!]!
    userGetFbeetsBalance: GqlUserFbeetsBalance!
    userGetStaking: [GqlPoolStaking!]!
    userGetPoolJoinExits(first: Int = 10, skip: Int = 0, poolId: String!): [GqlPoolJoinExit!]!
    userGetSwaps(first: Int = 10, skip: Int = 0, poolId: String!): [GqlPoolSwap!]!
}

extend type Mutation {
    userSyncBalance(poolId: String!): String!

    userInitWalletBalancesForAllPools: String!
    userInitWalletBalancesForPool(poolId: String!): String!
    userSyncWalletBalancesForAllPools: String!

    userInitStakedBalances: String!
    userSyncStakedBalances: String!
}

type GqlUserPoolBalance {
    poolId: String!
    tokenAddress: String!
    tokenPrice: Float!
    totalBalance: AmountHumanReadable!
    walletBalance: AmountHumanReadable!
    stakedBalance: AmountHumanReadable!
}

type GqlUserFbeetsBalance {
    id: String!
    totalBalance: AmountHumanReadable!
    walletBalance: AmountHumanReadable!
    stakedBalance: AmountHumanReadable!
}
