extend type Query {
    veBalGetUserBalance: AmountHumanReadable!
    veBalGetTotalSupply: AmountHumanReadable!
}

extend type Mutation {
    veBalSyncAllUserBalances: String!
    veBalSyncTotalSupply: String!
}
