extend type Query {
    veBalGetUserBalance: AmountHumanReadable!
    veBalGetTotalSupply: AmountHumanReadable!
    veBalGetVotingList: [GqlVotingPool!]!
    veBalGetUser: GqlVeBalUserData!
}

extend type Mutation {
    veBalSyncAllUserBalances: String!
    veBalSyncTotalSupply: String!
}

type GqlVeBalUserData {
    balance: AmountHumanReadable!
    rank: Int
}

type GqlVotingPool {
    id: ID!
    chain: GqlChain!
    symbol: String!
    address: Bytes!
    type: GqlPoolMinimalType!

    tokens: [GqlVotingGaugeToken!]!

    gauge: GqlVotingGauge!
}

type GqlVotingGaugeToken {
    address: String!
    weight: String
    symbol: String!
    logoURI: String!
}

type GqlVotingGauge {
    address: Bytes!
    childGaugeAddress: Bytes
    relativeWeightCap: String
    isKilled: Boolean!
    addedTimestamp: Int
}
