extend type Query {
    blocksGetAverageBlockTime: Float!
    blocksGetBlocksPerSecond: Float!
    blocksGetBlocksPerDay: Float!
    blocksGetBlocksPerYear: Float!
}

extend type Mutation {
    cacheAverageBlockTime: String!
}
