extend type Query {
    contentGetNewsItems: [GqlContentNewsItem!]!
}

type GqlContentNewsItem {
    id: ID!
    timestamp: String!
    url: String!
    text: String!
    source: GqlContentNewsItemSource!
    image: String
    discussionUrl: String
}

enum GqlContentNewsItemSource {
    twitter
    discord
    medium
}
