extend type Query {
    gauges: [GqlGauge]
    gauge(poolId: ID): GqlGauge
    gaugesAllUserShares: [GqlGaugeUserShare!]!
    gaugesUserShares(poolId: ID!): GqlGaugeUserShare
}

type GqlGauge {
    id: ID!
    address: Bytes!
    totalSupply: BigDecimal!
    poolId: Bytes
    tokens: [GqlGaugeRewardToken!]!
    shares: [GqlGaugeShare!]!
}

type GqlGaugeRewardToken {
    address: Bytes!
    name: String!
    symbol: String!
    decimals: Int!
}

type GqlGaugeShare {
    userAddress: Bytes!
    amount: BigDecimal!
}

type GqlGaugeUserShare {
    gaugeAddress: Bytes!
    poolId: Bytes!
    amount: BigDecimal!
    tokens: [GqlGaugeRewardToken!]!
}
