extend type Query {
    gauges: [GqlGauge]
    gaugesAllUserShares: [GqlGaugeUserShare!]!
    gaugesUserShares(poolId: ID!): GqlGaugeUserShare
}

type GqlGauge {
    id: ID!
    address: Bytes!
    totalSupply: BigDecimal!
    poolId: Bytes
    tokens: [GqlGaugeRewardTokenWithEmissions!]!
    shares: [GqlGaugeShare!]!
}

type GqlGaugeRewardTokenWithEmissions {
    address: Bytes!
    name: String!
    symbol: String!
    decimals: Int!
    rewardsPerSecond: BigDecimal!
    rewardsPerDay: BigDecimal!
}

type GqlGaugeRewardToken {
    address: Bytes!
    name: String!
    symbol: String!
    decimals: Int!
}

type GqlGaugeShare {
    userAddress: Bytes!
    amount: BigDecimal!
}

type GqlGaugeUserShare {
    gaugeAddress: Bytes!
    poolId: Bytes!
    amount: BigDecimal!
    amountUSD: BigDecimal!
    tokens: [GqlGaugeRewardToken!]!
}
