extend type Query {
    tokenGetTokens: [GqlToken!]!
    tokenGetCurrentPrices: [GqlTokenPrice!]!
    tokenGetHistoricalPrices(addresses: [String!]!): [GqlHistoricalTokenPrice!]!
}

extend type Mutation {
    tokenReloadTokenPrices: Boolean
    tokenSyncTokenDefinitions: String!
}

type GqlTokenPrice {
    address: String!
    price: Float!
}

type GqlHistoricalTokenPrice {
    address: String!
    prices: [GqlHistoricalTokenPriceEntry!]!
}

type GqlHistoricalTokenPriceEntry {
    timestamp: String!
    price: Float!
}

type GqlToken {
    address: String!
    name: String!
    symbol: String!
    decimals: Int!
    chainId: Int!
    logoURI: String
}
