extend type Query {
    portfolioGetUserPortfolio: GqlUserPortfolioData!
    portfolioGetUserPortfolioHistory: [GqlUserPortfolioData!]!
    portfolioGetUserPortfolioHistoryAdmin: [GqlUserPortfolioData!]!
}

extend type Mutation {
    cachePortfolioHistoryForDate(date: String!): Boolean!
    clearCacheAtBlock(block: Int!): Boolean!
    clearCachedPools: Boolean!
    clearCachedPortfolioHistories: Boolean!
    refreshLatestBlockCachedKey: Boolean!
}

type GqlUserPortfolioData {
    timestamp: Int!
    totalValue: GqlBigNumber!
    totalSwapFees: GqlBigNumber!
    totalSwapVolume: GqlBigNumber!
    myFees: GqlBigNumber!
    tokens: [GqlUserTokenData!]!
    pools: [GqlUserPoolData!]!
}

type GqlUserPoolData {
    id: String!
    poolId: String!
    poolAddress: String!
    name: String!
    shares: GqlBigNumber!
    percentShare: Float!
    totalValue: GqlBigNumber!
    pricePerShare: GqlBigNumber!
    tokens: [GqlUserTokenData!]!
    swapFees: GqlBigNumber!
    swapVolume: GqlBigNumber!
    myFees: GqlBigNumber!
    percentOfPortfolio: Float!
    priceChange: GqlBigNumber!
    priceChangePercent: Float!
}

type GqlUserTokenData {
    id: String!
    address: String!
    symbol: String!
    name: String!
    balance: GqlBigNumber!
    pricePerToken: GqlBigNumber!
    totalValue: GqlBigNumber!
    percentOfPortfolio: Float!
}
